export class customDelivery{
    bid:string;
    po_num :string;
    irnNumber:string;
    irnDate:string;
    invoiceNumber:string;
    invoiceDate:string;
    rateperquantity:string;
    lineItemNumber:string;
    lineitemtext:string;
    orderNumber:string;
    beforesubmissioninvoicenumber:string;
    businessPartnerText:string;
    contactPerson:string;
    buyerid:string;
    quantity:string;
    uOM:string;
    contactPersonPhone:string;
    vendorID:string;
    company:string;
    plant:string;
    department:string;
    storagelocation:string;
    costCentre:string;
    category:string;
    profileID:string;
    invoiceDocumentPath:string;
    iGSTAmount:string;
    cGSTAmount:string;
    sgstAmount:string;
    servicenumber:string;
    grnnumber:string;
    uniquereferencenumber:string;
    saplineitemnumber:string;
    srcnnumber:string;
    totalAmount:string;
    description:string;
    remark:string;
    totalamtinctaxes:string;
    taxamount:string;
    status:string;
    actualfilename:string;
    savedfilename: string;
    material: string;
    createdby: string;
    managerid: string;
    billofladingdate: string;
    balance_qty: any;
    invoiceamount: any;
    multiplesavedfilename: string;
    multipleactualfilename: string;
    stage: any;
    type: string;
    previnvno: string;
    prevponos: string;
    invoicetype: string;
}
